package com.sts.entity;

import java.util.List;

import com.sts.enums.EmployeeStatus;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import lombok.Data;
import lombok.NonNull;

@Entity
@Data
@Table(name = "employees")
public class Employee
{
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @OneToOne
    @JoinColumn(name = "user_id")
    private User user; // Assuming User class exists

    @Column
    private String specialization;

    @NonNull
    @Enumerated(EnumType.STRING)
    private EmployeeStatus status; // AVAILABLE, BUSY, ON_ROUTE, OFFLINE

    @OneToMany(mappedBy = "assignedEmployee", cascade = CascadeType.ALL)
    private List<Ticket> assignedTickets; // Assuming Ticket class exists

    @OneToMany(mappedBy = "employee", cascade = CascadeType.ALL)
    private List<Review> reviews; // Assuming Review class exists

    @OneToOne(mappedBy = "employee", cascade = CascadeType.ALL)
    private Location currentLocation; // Assuming Location class exists

    @Column
    private Double averageRating;

    @Column
    private Integer totalReviews;

    // Constructors, getters, and setters are automatically generated by Lombok's @Data annotation.
    // If you need custom constructors or specific getters/setters, you would add them here.
}
